image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements-dev.txt

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 kidsdata

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint -d C0301 kidsdata
