repos:
-   repo: https://github.com/psf/black
    rev: 20.8b0
    hooks:
    - id: black
      args: [--line-length=120]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
