"""initial rev

Revision ID: 275c7d9be197
Revises: 
Create Date: 2021-02-23 14:43:22.516662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275c7d9be197'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('param',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=False),
    sa.Column('param_hash', sa.String(length=64), nullable=False),
    sa.Column('nomexp', sa.String(length=200), nullable=True),
    sa.Column('acqfreq', sa.Float(), nullable=True),
    sa.Column('div_kid', sa.Integer(), nullable=True),
    sa.Column('raw_data_detector', sa.Text(), nullable=True),
    sa.Column('data_sc', sa.Text(), nullable=True),
    sa.Column('data_sd', sa.Text(), nullable=True),
    sa.Column('data_uc', sa.Text(), nullable=True),
    sa.Column('data_ud', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('param_hash')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kidpar',
    sa.Column('file_path', sa.String(length=4096), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=4096), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('param_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['param_id'], ['param.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('shifts',
    sa.Column('position_shift', sa.Float(), nullable=True),
    sa.Column('laser_shift', sa.Float(), nullable=True),
    sa.Column('zpd', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('astro',
    sa.Column('scan', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('obsmode', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_x_product',
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('scan_id', 'product_id')
    )
    op.create_table('tablebt',
    sa.Column('scan', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tablebt')
    op.drop_table('scan_x_product')
    op.drop_table('manual')
    op.drop_table('astro')
    op.drop_table('shifts')
    op.drop_table('scan')
    op.drop_table('kidpar')
    op.drop_table('stats')
    op.drop_table('product')
    op.drop_table('param')
    # ### end Alembic commands ###
